// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/nutanix-cloud-native/prism-go-client/nusights/models"
)

// PutConfigDataReader is a Reader for the PutConfigData structure.
type PutConfigDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutConfigDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutConfigDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutConfigDataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutConfigDataOK creates a PutConfigDataOK with default headers values
func NewPutConfigDataOK() *PutConfigDataOK {
	return &PutConfigDataOK{}
}

/*
PutConfigDataOK describes a response with status code 200, with default header values.

Config data added successfully.
*/
type PutConfigDataOK struct {
	Payload *PutConfigDataOKBody
}

// IsSuccess returns true when this put config data o k response has a 2xx status code
func (o *PutConfigDataOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put config data o k response has a 3xx status code
func (o *PutConfigDataOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put config data o k response has a 4xx status code
func (o *PutConfigDataOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put config data o k response has a 5xx status code
func (o *PutConfigDataOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put config data o k response a status code equal to that given
func (o *PutConfigDataOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put config data o k response
func (o *PutConfigDataOK) Code() int {
	return 200
}

func (o *PutConfigDataOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /entities][%d] putConfigDataOK %s", 200, payload)
}

func (o *PutConfigDataOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /entities][%d] putConfigDataOK %s", 200, payload)
}

func (o *PutConfigDataOK) GetPayload() *PutConfigDataOKBody {
	return o.Payload
}

func (o *PutConfigDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PutConfigDataOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutConfigDataDefault creates a PutConfigDataDefault with default headers values
func NewPutConfigDataDefault(code int) *PutConfigDataDefault {
	return &PutConfigDataDefault{
		_statusCode: code,
	}
}

/*
PutConfigDataDefault describes a response with status code -1, with default header values.

Failed to config data.
*/
type PutConfigDataDefault struct {
	_statusCode int

	Payload *PutConfigDataDefaultBody
}

// IsSuccess returns true when this put config data default response has a 2xx status code
func (o *PutConfigDataDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put config data default response has a 3xx status code
func (o *PutConfigDataDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put config data default response has a 4xx status code
func (o *PutConfigDataDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put config data default response has a 5xx status code
func (o *PutConfigDataDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put config data default response a status code equal to that given
func (o *PutConfigDataDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put config data default response
func (o *PutConfigDataDefault) Code() int {
	return o._statusCode
}

func (o *PutConfigDataDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /entities][%d] put_config_data default %s", o._statusCode, payload)
}

func (o *PutConfigDataDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /entities][%d] put_config_data default %s", o._statusCode, payload)
}

func (o *PutConfigDataDefault) GetPayload() *PutConfigDataDefaultBody {
	return o.Payload
}

func (o *PutConfigDataDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PutConfigDataDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
PutConfigDataDefaultBody put config data default body
swagger:model PutConfigDataDefaultBody
*/
type PutConfigDataDefaultBody struct {

	// entities
	Entities []*models.EntityErrorObject `json:"entities"`

	// message
	Message string `json:"message,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PutConfigDataDefaultBody) UnmarshalJSON(raw []byte) error {
	// PutConfigDataDefaultBodyAO0
	var dataPutConfigDataDefaultBodyAO0 struct {
		Entities []*models.EntityErrorObject `json:"entities"`

		Message string `json:"message,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPutConfigDataDefaultBodyAO0); err != nil {
		return err
	}

	o.Entities = dataPutConfigDataDefaultBodyAO0.Entities

	o.Message = dataPutConfigDataDefaultBodyAO0.Message

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PutConfigDataDefaultBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataPutConfigDataDefaultBodyAO0 struct {
		Entities []*models.EntityErrorObject `json:"entities"`

		Message string `json:"message,omitempty"`
	}

	dataPutConfigDataDefaultBodyAO0.Entities = o.Entities

	dataPutConfigDataDefaultBodyAO0.Message = o.Message

	jsonDataPutConfigDataDefaultBodyAO0, errPutConfigDataDefaultBodyAO0 := swag.WriteJSON(dataPutConfigDataDefaultBodyAO0)
	if errPutConfigDataDefaultBodyAO0 != nil {
		return nil, errPutConfigDataDefaultBodyAO0
	}
	_parts = append(_parts, jsonDataPutConfigDataDefaultBodyAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this put config data default body
func (o *PutConfigDataDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEntities(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutConfigDataDefaultBody) validateEntities(formats strfmt.Registry) error {

	if swag.IsZero(o.Entities) { // not required
		return nil
	}

	for i := 0; i < len(o.Entities); i++ {
		if swag.IsZero(o.Entities[i]) { // not required
			continue
		}

		if o.Entities[i] != nil {
			if err := o.Entities[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("put_config_data default" + "." + "entities" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("put_config_data default" + "." + "entities" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this put config data default body based on the context it is used
func (o *PutConfigDataDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateEntities(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutConfigDataDefaultBody) contextValidateEntities(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Entities); i++ {

		if o.Entities[i] != nil {

			if swag.IsZero(o.Entities[i]) { // not required
				return nil
			}

			if err := o.Entities[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("put_config_data default" + "." + "entities" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("put_config_data default" + "." + "entities" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutConfigDataDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutConfigDataDefaultBody) UnmarshalBinary(b []byte) error {
	var res PutConfigDataDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
PutConfigDataOKBody put config data o k body
swagger:model PutConfigDataOKBody
*/
type PutConfigDataOKBody struct {

	// message
	// Example: All entities added to Kinesis/S3 successfully
	Message string `json:"message,omitempty"`
}

// Validate validates this put config data o k body
func (o *PutConfigDataOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put config data o k body based on context it is used
func (o *PutConfigDataOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutConfigDataOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutConfigDataOKBody) UnmarshalBinary(b []byte) error {
	var res PutConfigDataOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
