version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - nolintlint
    - staticcheck
    - unused
linters-settings:
  nolintlint:
    require-explanation: true
    require-specific: true
run:
  concurrency: 4
  timeout: 5m
