// Code generated by MockGen. DO NOT EDIT.
// Source: converged_client/storage_containers.go
//
// Generated by this command:
//
//	mockgen -source=converged_client/storage_containers.go -destination=converged_client/mocks/storage_containers_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	convergedclient "github.com/nutanix-cloud-native/prism-go-client/converged_client"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageContainers is a mock of StorageContainers interface.
type MockStorageContainers[StorageContainer any] struct {
	ctrl     *gomock.Controller
	recorder *MockStorageContainersMockRecorder[StorageContainer]
	isgomock struct{}
}

// MockStorageContainersMockRecorder is the mock recorder for MockStorageContainers.
type MockStorageContainersMockRecorder[StorageContainer any] struct {
	mock *MockStorageContainers[StorageContainer]
}

// NewMockStorageContainers creates a new mock instance.
func NewMockStorageContainers[StorageContainer any](ctrl *gomock.Controller) *MockStorageContainers[StorageContainer] {
	mock := &MockStorageContainers[StorageContainer]{ctrl: ctrl}
	mock.recorder = &MockStorageContainersMockRecorder[StorageContainer]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageContainers[StorageContainer]) EXPECT() *MockStorageContainersMockRecorder[StorageContainer] {
	return m.recorder
}

// Get mocks base method.
func (m *MockStorageContainers[StorageContainer]) Get(ctx context.Context, uuid string) (*StorageContainer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*StorageContainer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageContainersMockRecorder[StorageContainer]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorageContainers[StorageContainer])(nil).Get), ctx, uuid)
}

// List mocks base method.
func (m *MockStorageContainers[StorageContainer]) List(ctx context.Context, opts ...convergedclient.ODataOption) ([]StorageContainer, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]StorageContainer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStorageContainersMockRecorder[StorageContainer]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStorageContainers[StorageContainer])(nil).List), varargs...)
}

// ListAll mocks base method.
func (m *MockStorageContainers[StorageContainer]) ListAll(ctx context.Context, opts ...convergedclient.ODataOption) ([]StorageContainer, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAll", varargs...)
	ret0, _ := ret[0].([]StorageContainer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockStorageContainersMockRecorder[StorageContainer]) ListAll(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockStorageContainers[StorageContainer])(nil).ListAll), varargs...)
}

// NewIterator mocks base method.
func (m *MockStorageContainers[StorageContainer]) NewIterator(ctx any, opts ...convergedclient.ODataOption) convergedclient.Iterator[StorageContainer] {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(convergedclient.Iterator[StorageContainer])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockStorageContainersMockRecorder[StorageContainer]) NewIterator(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockStorageContainers[StorageContainer])(nil).NewIterator), opts...)
}
