//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package credentials

import (
	"encoding/json"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuth) DeepCopyInto(out *BasicAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuth.
func (in *BasicAuth) DeepCopy() *BasicAuth {
	if in == nil {
		return nil
	}
	out := new(BasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credential) DeepCopyInto(out *Credential) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credential.
func (in *Credential) DeepCopy() *Credential {
	if in == nil {
		return nil
	}
	out := new(Credential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixCredentialReference) DeepCopyInto(out *NutanixCredentialReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixCredentialReference.
func (in *NutanixCredentialReference) DeepCopy() *NutanixCredentialReference {
	if in == nil {
		return nil
	}
	out := new(NutanixCredentialReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixCredentials) DeepCopyInto(out *NutanixCredentials) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]Credential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixCredentials.
func (in *NutanixCredentials) DeepCopy() *NutanixCredentials {
	if in == nil {
		return nil
	}
	out := new(NutanixCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixPrismEndpoint) DeepCopyInto(out *NutanixPrismEndpoint) {
	*out = *in
	if in.CredentialRef != nil {
		in, out := &in.CredentialRef, &out.CredentialRef
		*out = new(NutanixCredentialReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixPrismEndpoint.
func (in *NutanixPrismEndpoint) DeepCopy() *NutanixPrismEndpoint {
	if in == nil {
		return nil
	}
	out := new(NutanixPrismEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrismCentralBasicAuth) DeepCopyInto(out *PrismCentralBasicAuth) {
	*out = *in
	out.BasicAuth = in.BasicAuth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrismCentralBasicAuth.
func (in *PrismCentralBasicAuth) DeepCopy() *PrismCentralBasicAuth {
	if in == nil {
		return nil
	}
	out := new(PrismCentralBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrismElementBasicAuth) DeepCopyInto(out *PrismElementBasicAuth) {
	*out = *in
	out.BasicAuth = in.BasicAuth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrismElementBasicAuth.
func (in *PrismElementBasicAuth) DeepCopy() *PrismElementBasicAuth {
	if in == nil {
		return nil
	}
	out := new(PrismElementBasicAuth)
	in.DeepCopyInto(out)
	return out
}
