// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EntitiesCollection Input for  Entities API call.
//
// Details for input object for sending entities.
//
// swagger:model entities_collection
type EntitiesCollection struct {

	// entities list
	// Required: true
	// Min Items: 1
	EntitiesList []*Entity `json:"entities"`

	// Additional attributes thats applicable to all entities can
	// be specified at top level. All those attributes will be added to every
	// entity's attribute data Map. A max of 850 key, value pairs including
	// global and per entity key-value pairs can be added.
	//
	EntitiesCollection map[string]any `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *EntitiesCollection) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// entities list
		// Required: true
		// Min Items: 1
		EntitiesList []*Entity `json:"entities"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv EntitiesCollection

	rcv.EntitiesList = stage1.EntitiesList
	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "entities_list")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]any)
		for k, v := range stage2 {
			var toadd any
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.EntitiesCollection = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m EntitiesCollection) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// entities list
		// Required: true
		// Min Items: 1
		EntitiesList []*Entity `json:"entities"`
	}

	stage1.EntitiesList = m.EntitiesList

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.EntitiesCollection) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.EntitiesCollection)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this entities collection
func (m *EntitiesCollection) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEntitiesList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EntitiesCollection) validateEntitiesList(formats strfmt.Registry) error {

	if err := validate.Required("entities", "body", m.EntitiesList); err != nil {
		return err
	}

	iEntitiesListSize := int64(len(m.EntitiesList))

	if err := validate.MinItems("entities", "body", iEntitiesListSize, 1); err != nil {
		return err
	}

	for i := 0; i < len(m.EntitiesList); i++ {
		if swag.IsZero(m.EntitiesList[i]) { // not required
			continue
		}

		if m.EntitiesList[i] != nil {
			if err := m.EntitiesList[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("entities" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("entities" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this entities collection based on the context it is used
func (m *EntitiesCollection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEntitiesList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EntitiesCollection) contextValidateEntitiesList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.EntitiesList); i++ {

		if m.EntitiesList[i] != nil {

			if swag.IsZero(m.EntitiesList[i]) { // not required
				return nil
			}

			if err := m.EntitiesList[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("entities" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("entities" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EntitiesCollection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntitiesCollection) UnmarshalBinary(b []byte) error {
	var res EntitiesCollection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
