// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Entity Input for Entities API call.
//
// Details for each entity input object.
//
// swagger:model entity
type Entity struct {

	// Timestamp in usecs when the entity was created.
	// Example: 1553721422000000
	// Minimum: 0
	CreatedTimestampUsecs *int64 `json:"created_timestamp_usecs,omitempty"`

	// Timestamp in usecs when the entity was deleted.
	// Example: 1553721622000000
	// Minimum: 0
	DeletedTimestampUsecs *int64 `json:"deleted_timestamp_usecs,omitempty"`

	// Entity Id of the entity being consumed.
	// Example: 14cbe61c2-182e-43d6-bd4a-b04e8c02e5c1:1
	// Required: true
	// Min Length: 1
	EntityID *string `json:"entity_id"`

	// Type of the entity being consumed.
	// Example: vmms_taskstep
	// Required: true
	// Min Length: 1
	EntityType *string `json:"entity_type"`

	// Entity Namespace. If not specified, 'default' namespace
	// will be used for entity.
	//
	// Example: vcenter
	Namespace string `json:"namespace,omitempty"`

	// Timestamp when the the entity is modified. This timestamp can be no
	// more than 5 minutes into future. If the client clock is incorrectly
	// configured to a future time, the updates will be rejected by the API
	//
	// Example: 1553721622000000
	// Required: true
	// Minimum: 1.468425246e+15
	TimestampUsecs *int64 `json:"timestamp_usecs"`

	// Additional attributes thats applicable to a particular
	// entity can be specified. These will be copied to entity
	// attribute's data map.A max of 850 key, value pairs including
	// global and per entity key-value pairs can be added.
	//
	Entity map[string]any `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *Entity) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// Timestamp in usecs when the entity was created.
		// Example: 1553721422000000
		// Minimum: 0
		CreatedTimestampUsecs *int64 `json:"created_timestamp_usecs,omitempty"`

		// Timestamp in usecs when the entity was deleted.
		// Example: 1553721622000000
		// Minimum: 0
		DeletedTimestampUsecs *int64 `json:"deleted_timestamp_usecs,omitempty"`

		// Entity Id of the entity being consumed.
		// Example: 14cbe61c2-182e-43d6-bd4a-b04e8c02e5c1:1
		// Required: true
		// Min Length: 1
		EntityID *string `json:"entity_id"`

		// Type of the entity being consumed.
		// Example: vmms_taskstep
		// Required: true
		// Min Length: 1
		EntityType *string `json:"entity_type"`

		// Entity Namespace. If not specified, 'default' namespace
		// will be used for entity.
		//
		// Example: vcenter
		Namespace string `json:"namespace,omitempty"`

		// Timestamp when the the entity is modified. This timestamp can be no
		// more than 5 minutes into future. If the client clock is incorrectly
		// configured to a future time, the updates will be rejected by the API
		//
		// Example: 1553721622000000
		// Required: true
		// Minimum: 1.468425246e+15
		TimestampUsecs *int64 `json:"timestamp_usecs"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv Entity

	rcv.CreatedTimestampUsecs = stage1.CreatedTimestampUsecs
	rcv.DeletedTimestampUsecs = stage1.DeletedTimestampUsecs
	rcv.EntityID = stage1.EntityID
	rcv.EntityType = stage1.EntityType
	rcv.Namespace = stage1.Namespace
	rcv.TimestampUsecs = stage1.TimestampUsecs
	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "created_timestamp_usecs")
	delete(stage2, "deleted_timestamp_usecs")
	delete(stage2, "entity_id")
	delete(stage2, "entity_type")
	delete(stage2, "namespace")
	delete(stage2, "timestamp_usecs")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]any)
		for k, v := range stage2 {
			var toadd any
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.Entity = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m Entity) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// Timestamp in usecs when the entity was created.
		// Example: 1553721422000000
		// Minimum: 0
		CreatedTimestampUsecs *int64 `json:"created_timestamp_usecs,omitempty"`

		// Timestamp in usecs when the entity was deleted.
		// Example: 1553721622000000
		// Minimum: 0
		DeletedTimestampUsecs *int64 `json:"deleted_timestamp_usecs,omitempty"`

		// Entity Id of the entity being consumed.
		// Example: 14cbe61c2-182e-43d6-bd4a-b04e8c02e5c1:1
		// Required: true
		// Min Length: 1
		EntityID *string `json:"entity_id"`

		// Type of the entity being consumed.
		// Example: vmms_taskstep
		// Required: true
		// Min Length: 1
		EntityType *string `json:"entity_type"`

		// Entity Namespace. If not specified, 'default' namespace
		// will be used for entity.
		//
		// Example: vcenter
		Namespace string `json:"namespace,omitempty"`

		// Timestamp when the the entity is modified. This timestamp can be no
		// more than 5 minutes into future. If the client clock is incorrectly
		// configured to a future time, the updates will be rejected by the API
		//
		// Example: 1553721622000000
		// Required: true
		// Minimum: 1.468425246e+15
		TimestampUsecs *int64 `json:"timestamp_usecs"`
	}

	stage1.CreatedTimestampUsecs = m.CreatedTimestampUsecs
	stage1.DeletedTimestampUsecs = m.DeletedTimestampUsecs
	stage1.EntityID = m.EntityID
	stage1.EntityType = m.EntityType
	stage1.Namespace = m.Namespace
	stage1.TimestampUsecs = m.TimestampUsecs

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.Entity) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.Entity)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this entity
func (m *Entity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedTimestampUsecs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeletedTimestampUsecs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntityID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntityType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestampUsecs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Entity) validateCreatedTimestampUsecs(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedTimestampUsecs) { // not required
		return nil
	}

	if err := validate.MinimumInt("created_timestamp_usecs", "body", *m.CreatedTimestampUsecs, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *Entity) validateDeletedTimestampUsecs(formats strfmt.Registry) error {
	if swag.IsZero(m.DeletedTimestampUsecs) { // not required
		return nil
	}

	if err := validate.MinimumInt("deleted_timestamp_usecs", "body", *m.DeletedTimestampUsecs, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *Entity) validateEntityID(formats strfmt.Registry) error {

	if err := validate.Required("entity_id", "body", m.EntityID); err != nil {
		return err
	}

	if err := validate.MinLength("entity_id", "body", *m.EntityID, 1); err != nil {
		return err
	}

	return nil
}

func (m *Entity) validateEntityType(formats strfmt.Registry) error {

	if err := validate.Required("entity_type", "body", m.EntityType); err != nil {
		return err
	}

	if err := validate.MinLength("entity_type", "body", *m.EntityType, 1); err != nil {
		return err
	}

	return nil
}

func (m *Entity) validateTimestampUsecs(formats strfmt.Registry) error {

	if err := validate.Required("timestamp_usecs", "body", m.TimestampUsecs); err != nil {
		return err
	}

	if err := validate.MinimumInt("timestamp_usecs", "body", *m.TimestampUsecs, 1.468425246e+15, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this entity based on context it is used
func (m *Entity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Entity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Entity) UnmarshalBinary(b []byte) error {
	var res Entity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
