// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EntityErrorObject Error info for failed entity.
//
// Details on which entities failed and error reason for each
// of them.
//
// swagger:model entity_error_object
type EntityErrorObject struct {

	// entity id
	// Required: true
	EntityID *string `json:"entity_id"`

	// entity type
	// Example: vmms_taskstep
	// Required: true
	EntityType *string `json:"entity_type"`

	// namespace
	// Example: vcenter
	Namespace string `json:"namespace,omitempty"`

	Error
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *EntityErrorObject) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		EntityID *string `json:"entity_id"`

		EntityType *string `json:"entity_type"`

		Namespace string `json:"namespace,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.EntityID = dataAO0.EntityID

	m.EntityType = dataAO0.EntityType

	m.Namespace = dataAO0.Namespace

	// AO1
	var aO1 Error
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.Error = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m EntityErrorObject) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		EntityID *string `json:"entity_id"`

		EntityType *string `json:"entity_type"`

		Namespace string `json:"namespace,omitempty"`
	}

	dataAO0.EntityID = m.EntityID

	dataAO0.EntityType = m.EntityType

	dataAO0.Namespace = m.Namespace

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)

	aO1, err := swag.WriteJSON(m.Error)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this entity error object
func (m *EntityErrorObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEntityID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntityType(formats); err != nil {
		res = append(res, err)
	}

	// validation for a type composition with Error
	if err := m.Error.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EntityErrorObject) validateEntityID(formats strfmt.Registry) error {

	if err := validate.Required("entity_id", "body", m.EntityID); err != nil {
		return err
	}

	return nil
}

func (m *EntityErrorObject) validateEntityType(formats strfmt.Registry) error {

	if err := validate.Required("entity_type", "body", m.EntityType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this entity error object based on the context it is used
func (m *EntityErrorObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Error
	if err := m.Error.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *EntityErrorObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EntityErrorObject) UnmarshalBinary(b []byte) error {
	var res EntityErrorObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
