// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CustomGenericKeyValuePair Generic key value pair
//
// # Generic key value pair used for custom attributes
//
// swagger:model custom_generic_key_value_pair
type CustomGenericKeyValuePair map[string]string

// Validate validates this custom generic key value pair
func (m CustomGenericKeyValuePair) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this custom generic key value pair based on context it is used
func (m CustomGenericKeyValuePair) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
