// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DiskAddress Disk Address
//
// Disk Address.
//
// swagger:model disk_address
type DiskAddress struct {

	// adapter type
	// Required: true
	AdapterType *string `json:"adapter_type"`

	// device index
	// Required: true
	DeviceIndex *int64 `json:"device_index"`
}

// Validate validates this disk address
func (m *DiskAddress) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdapterType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeviceIndex(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiskAddress) validateAdapterType(formats strfmt.Registry) error {

	if err := validate.Required("adapter_type", "body", m.AdapterType); err != nil {
		return err
	}

	return nil
}

func (m *DiskAddress) validateDeviceIndex(formats strfmt.Registry) error {

	if err := validate.Required("device_index", "body", m.DeviceIndex); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this disk address based on context it is used
func (m *DiskAddress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DiskAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiskAddress) UnmarshalBinary(b []byte) error {
	var res DiskAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
