// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// FlashMode Flash Mode
//
// State of the storage policy to pin virtual disks to the hot tier.
// When specified as a VM attribute, the storage policy applies to all
// virtual disks of the VM unless overridden by the same attribute
// specified for a virtual disk.
//
// swagger:model flash_mode
type FlashMode string

// Validate validates this flash mode
func (m FlashMode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this flash mode based on context it is used
func (m FlashMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
