// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GuestToolsStatus Guest Tools information
//
// Information regarding guest tools.
//
// swagger:model guest_tools_status
type GuestToolsStatus struct {

	// Nutanix Guest Tools information
	NutanixGuestTools *NutanixGuestToolsStatus `json:"nutanix_guest_tools,omitempty"`
}

// Validate validates this guest tools status
func (m *GuestToolsStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNutanixGuestTools(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GuestToolsStatus) validateNutanixGuestTools(formats strfmt.Registry) error {
	if swag.IsZero(m.NutanixGuestTools) { // not required
		return nil
	}

	if m.NutanixGuestTools != nil {
		if err := m.NutanixGuestTools.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nutanix_guest_tools")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("nutanix_guest_tools")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this guest tools status based on the context it is used
func (m *GuestToolsStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNutanixGuestTools(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GuestToolsStatus) contextValidateNutanixGuestTools(ctx context.Context, formats strfmt.Registry) error {

	if m.NutanixGuestTools != nil {

		if swag.IsZero(m.NutanixGuestTools) { // not required
			return nil
		}

		if err := m.NutanixGuestTools.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nutanix_guest_tools")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("nutanix_guest_tools")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GuestToolsStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GuestToolsStatus) UnmarshalBinary(b []byte) error {
	var res GuestToolsStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
