// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NutanixGuestToolsStatus Nutanix Guest Tools status
//
// Information regarding Nutanix Guest Tools.
//
// swagger:model nutanix_guest_tools_status
type NutanixGuestToolsStatus struct {

	// Version of Nutanix Guest Tools available on the cluster.
	AvailableVersion string `json:"available_version,omitempty"`

	// Administrator Credentials of UVM. This is required for installing Nutanix Guest Tools on the UVM.
	//
	Credentials *Credentials `json:"credentials,omitempty"`

	// Application names that are enabled.
	EnabledCapabilityList []string `json:"enabled_capability_list"`

	// Version of the operating system on the VM.
	GuestOsVersion string `json:"guest_os_version,omitempty"`

	// Communication from VM to CVM is active or not.
	IsReachable bool `json:"is_reachable,omitempty"`

	// Desired mount state of Nutanix Guest Tools ISO.
	//
	IsoMountState string `json:"iso_mount_state,omitempty"`

	// Nutanix guest tools is installed or not.
	NgtState string `json:"ngt_state,omitempty"`

	// Nutanix Guest Tools is enabled or not.
	State string `json:"state,omitempty"`

	// Version of Nutanix Guest Tools installed on the VM.
	Version string `json:"version,omitempty"`

	// Whether VM mobility drivers are installed in the VM.
	VMMobilityDriversInstalled bool `json:"vm_mobility_drivers_installed,omitempty"`

	// Whether the VM is configured to take VSS snapshots through NGT.
	//
	VssSnapshotCapable bool `json:"vss_snapshot_capable,omitempty"`
}

// Validate validates this nutanix guest tools status
func (m *NutanixGuestToolsStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCredentials(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NutanixGuestToolsStatus) validateCredentials(formats strfmt.Registry) error {
	if swag.IsZero(m.Credentials) { // not required
		return nil
	}

	if m.Credentials != nil {
		if err := m.Credentials.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("credentials")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("credentials")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this nutanix guest tools status based on the context it is used
func (m *NutanixGuestToolsStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCredentials(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NutanixGuestToolsStatus) contextValidateCredentials(ctx context.Context, formats strfmt.Registry) error {

	if m.Credentials != nil {

		if swag.IsZero(m.Credentials) { // not required
			return nil
		}

		if err := m.Credentials.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("credentials")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("credentials")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NutanixGuestToolsStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NutanixGuestToolsStatus) UnmarshalBinary(b []byte) error {
	var res NutanixGuestToolsStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
