// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PolicyComplianceState Policy Compliance State Enum
//
// Compliance state enum.
//
// swagger:model policy_compliance_state
type PolicyComplianceState string

// Validate validates this policy compliance state
func (m PolicyComplianceState) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this policy compliance state based on context it is used
func (m PolicyComplianceState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
