// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProtectionInfo Protection policy information.
//
// Information about state of the policy.
//
// swagger:model protection_info
type ProtectionInfo struct {

	// Replication status of the entity.
	//
	ReplicationStatus string `json:"replication_status,omitempty"`
}

// Validate validates this protection info
func (m *ProtectionInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this protection info based on context it is used
func (m *ProtectionInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProtectionInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProtectionInfo) UnmarshalBinary(b []byte) error {
	var res ProtectionInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
