// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SerialPort VM serial port connection.
//
// Indicates the configuration of serial ports of the VM.
//
// swagger:model serial_port
type SerialPort struct {

	// Index of the serial port.
	Index int64 `json:"index,omitempty"`

	// Indicates whether the serial port connection is connected or not.
	//
	IsConnected bool `json:"is_connected,omitempty"`
}

// Validate validates this serial port
func (m *SerialPort) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this serial port based on context it is used
func (m *SerialPort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SerialPort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SerialPort) UnmarshalBinary(b []byte) error {
	var res SerialPort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
