// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StorageQosPolicyConfigInput Storage Qos Configuration Input
//
// # QoS parameters to be enforced
//
// swagger:model storage_qos_policy_config_input
type StorageQosPolicyConfigInput struct {

	// Throttled iops for the entities being governed.
	// The block size for the IO is 32kB.
	//
	// Required: true
	ThrottledIops *int64 `json:"throttled_iops"`
}

// Validate validates this storage qos policy config input
func (m *StorageQosPolicyConfigInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateThrottledIops(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StorageQosPolicyConfigInput) validateThrottledIops(formats strfmt.Registry) error {

	if err := validate.Required("throttled_iops", "body", m.ThrottledIops); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this storage qos policy config input based on context it is used
func (m *StorageQosPolicyConfigInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageQosPolicyConfigInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageQosPolicyConfigInput) UnmarshalBinary(b []byte) error {
	var res StorageQosPolicyConfigInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
