// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorageQosPolicyConfigOutput Storage Qos Configuration Output
//
// # QoS parameters being enforced
//
// swagger:model storage_qos_policy_config_output
type StorageQosPolicyConfigOutput struct {

	// Throttled iops for the entities being governed.
	// The block size for the IO is 32kB.
	//
	ThrottledIops int64 `json:"throttled_iops,omitempty"`
}

// Validate validates this storage qos policy config output
func (m *StorageQosPolicyConfigOutput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage qos policy config output based on context it is used
func (m *StorageQosPolicyConfigOutput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorageQosPolicyConfigOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageQosPolicyConfigOutput) UnmarshalBinary(b []byte) error {
	var res StorageQosPolicyConfigOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
