// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VMApcConfig VM APC Config
//
// Information about Advanced Processor Compatibility of VM to indicate whether to retain the CPU model for given VM or not across migrations.
//
// swagger:model vm_apc_config
type VMApcConfig struct {

	// Reference to basic information(uuid/name) of CPU model associated with VM.
	//
	CPUModelReference *Reference `json:"cpu_model_reference,omitempty"`

	// If enabled, the selected CPU model will be retained across live and cold migrations of the VM. If enabled and no CPU model is explicitly set, a baseline CPU model is picked. See the APC documentation for more information.
	//
	Enabled *bool `json:"enabled,omitempty"`
}

// Validate validates this vm apc config
func (m *VMApcConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCPUModelReference(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VMApcConfig) validateCPUModelReference(formats strfmt.Registry) error {
	if swag.IsZero(m.CPUModelReference) { // not required
		return nil
	}

	if m.CPUModelReference != nil {
		if err := m.CPUModelReference.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cpu_model_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cpu_model_reference")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this vm apc config based on the context it is used
func (m *VMApcConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCPUModelReference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VMApcConfig) contextValidateCPUModelReference(ctx context.Context, formats strfmt.Registry) error {

	if m.CPUModelReference != nil {

		if swag.IsZero(m.CPUModelReference) { // not required
			return nil
		}

		if err := m.CPUModelReference.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cpu_model_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cpu_model_reference")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VMApcConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VMApcConfig) UnmarshalBinary(b []byte) error {
	var res VMApcConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
