// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VMGpu VirtualMachine GPU
//
// Graphics resource information for the Virtual Machine.
//
// swagger:model vm_gpu
type VMGpu struct {

	// The device ID of the GPU.
	DeviceID int32 `json:"device_id,omitempty"`

	// The mode of this GPU.
	Mode string `json:"mode,omitempty"`

	// The vendor of the GPU.
	Vendor string `json:"vendor,omitempty"`
}

// Validate validates this vm gpu
func (m *VMGpu) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vm gpu based on context it is used
func (m *VMGpu) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VMGpu) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VMGpu) UnmarshalBinary(b []byte) error {
	var res VMGpu
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
