// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VMGuestPowerStateTransitionConfig Power State Transition Config
//
// Extra configs related to power state transition.
//
// swagger:model vm_guest_power_state_transition_config
type VMGuestPowerStateTransitionConfig struct {

	// Indicates whether to execute set script before ngt shutdown/reboot.
	EnableScriptExec bool `json:"enable_script_exec,omitempty"`

	// Indicates whether to abort ngt shutdown/reboot if script fails.
	ShouldFailOnScriptFailure bool `json:"should_fail_on_script_failure,omitempty"`
}

// Validate validates this vm guest power state transition config
func (m *VMGuestPowerStateTransitionConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vm guest power state transition config based on context it is used
func (m *VMGuestPowerStateTransitionConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VMGuestPowerStateTransitionConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VMGuestPowerStateTransitionConfig) UnmarshalBinary(b []byte) error {
	var res VMGuestPowerStateTransitionConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
