// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VMResourcesDefStatus VM Resources Status Definition
//
// VM Resources Status Definition.
//
// swagger:model vm_resources_def_status
type VMResourcesDefStatus struct {

	// Information about Advanced Processor Comptability(APC) setting of VM.
	//
	ApcConfig *VMApcConfig `json:"apc_config,omitempty"`

	// Indicates the BIOS UUID of the VM.
	// Pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
	BiosUUID string `json:"bios_uuid,omitempty"`

	// Indicates which device the VM should boot from.
	BootConfig *VMBootConfig `json:"boot_config,omitempty"`

	// Indicates whether to remove AHV branding from VM firmware tables.
	//
	DisableBranding bool `json:"disable_branding,omitempty"`

	// Disks attached to the VM.
	DiskList []*VMDiskOutputStatus `json:"disk_list"`

	// Effective storage configuration for AHV VMs.
	EffectiveStorageConfig *EffectiveStorageConfig `json:"effective_storage_config,omitempty"`

	// Indicates whether to passthrough the host's CPU features to the guest. Enabling this will disable live migration of the VM.
	//
	EnableCPUPassthrough bool `json:"enable_cpu_passthrough,omitempty"`

	// Indicates the Generation UUID of the VM.
	// Pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
	GenerationUUID string `json:"generation_uuid,omitempty"`

	// Indicates whether vGPU console is enabled or not.
	GpuConsoleEnabled bool `json:"gpu_console_enabled,omitempty"`

	// GPUs attached to the VM.
	GpuList []*VMGpuOutputStatus `json:"gpu_list"`

	// guest customization
	GuestCustomization *GuestCustomizationStatus `json:"guest_customization,omitempty"`

	// String that identifies the OS running inside of the guest. Reserved for use by the system. Do not set or modify.
	GuestOsID string `json:"guest_os_id,omitempty"`

	// Information regarding guest tools.
	GuestTools *GuestToolsStatus `json:"guest_tools,omitempty"`

	// VM's hardware clock timezone in IANA TZDB format (America/Los_Angeles).
	//
	HardwareClockTimezone string `json:"hardware_clock_timezone,omitempty"`

	// Indicates whether hardware assisted virtualization should be enabled for the Guest OS. Once enabled, the Guest OS has the ability to deploy a nested hypervisor.
	//
	HardwareVirtualizationEnabled bool `json:"hardware_virtualization_enabled,omitempty"`

	// host reference
	HostReference *Reference `json:"host_reference,omitempty"`

	// The hypervisor type for the hypervisor the VM is hosted on.
	//
	HypervisorType string `json:"hypervisor_type,omitempty"`

	// Indicates whether the VM is an agent VM.
	IsAgentVM bool `json:"is_agent_vm,omitempty"`

	// Indicates whether the vCPUs should be hard pinned to specific pCPUs.
	IsVcpuHardPinned bool `json:"is_vcpu_hard_pinned,omitempty"`

	// Machine type for the VM. Machine type Q35 is required for secure boot and does not support IDE disks.
	//
	MachineType string `json:"machine_type,omitempty"`

	// Indicates whether memory overcommit feature should be enabled for the VM. If enabled, parts of the VM's memory may reside outside of the hypervisor physical memory. When enabled, it should be expected that the VM may suffer performance degradation.
	//
	MemoryOvercommitEnabled bool `json:"memory_overcommit_enabled,omitempty"`

	// Memory size in MiB.
	// Minimum: 1
	MemorySizeMib int32 `json:"memory_size_mib,omitempty"`

	// NICs attached to the VM.
	NicList []*VMNicOutputStatus `json:"nic_list"`

	// Number of vCPU sockets.
	NumSockets int32 `json:"num_sockets,omitempty"`

	// Number of logical threads per core.
	// Minimum: 1
	NumThreadsPerCore int32 `json:"num_threads_per_core,omitempty"`

	// Number of vCPUs per socket.
	NumVcpusPerSocket int32 `json:"num_vcpus_per_socket,omitempty"`

	// Reference to an entity that the VM was cloned or created from.
	//
	ParentReference *Reference `json:"parent_reference,omitempty"`

	// Current power state of the VM.
	PowerState string `json:"power_state,omitempty"`

	// power state mechanism
	PowerStateMechanism *VMPowerStateMechanism `json:"power_state_mechanism,omitempty"`

	// Status of protection policy applied to this VM.
	//
	ProtectionPolicyState *ProtectionPolicyState `json:"protection_policy_state,omitempty"`

	// The type of protection applied on a VM. PD_PROTECTED indicates a VM protected using Prism Element. RULE_PROTECTED indicates a VM protected using Prism Central.
	//
	ProtectionType string `json:"protection_type,omitempty"`

	// Status of the Recovery Plans associated with the VM.
	RecoveryPlanStateList []*RecoveryPlanPolicyState `json:"recovery_plan_state_list"`

	// Serial ports configured on the VM.
	SerialPortList []*SerialPort `json:"serial_port_list"`

	// Current status of storage configuration for AHV VMs.
	StorageConfig *VMStorageConfigStatus `json:"storage_config,omitempty"`

	// Indicates whether VGA console has been enabled or not.
	VgaConsoleEnabled bool `json:"vga_console_enabled,omitempty"`

	// Information regarding vNUMA configuration.
	VnumaConfig *VMVnumaConfig `json:"vnuma_config,omitempty"`

	// VM vTPM configuration.
	VtpmConfig *VMVtpmStatus `json:"vtpm_config,omitempty"`
}

// Validate validates this vm resources def status
func (m *VMResourcesDefStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApcConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBiosUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBootConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiskList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEffectiveStorageConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGenerationUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGpuList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGuestCustomization(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGuestTools(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHostReference(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMemorySizeMib(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNicList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNumThreadsPerCore(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParentReference(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePowerStateMechanism(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtectionPolicyState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecoveryPlanStateList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSerialPortList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStorageConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVnumaConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVtpmConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VMResourcesDefStatus) validateApcConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.ApcConfig) { // not required
		return nil
	}

	if m.ApcConfig != nil {
		if err := m.ApcConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apc_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apc_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateBiosUUID(formats strfmt.Registry) error {
	if swag.IsZero(m.BiosUUID) { // not required
		return nil
	}

	if err := validate.Pattern("bios_uuid", "body", m.BiosUUID, `^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$`); err != nil {
		return err
	}

	return nil
}

func (m *VMResourcesDefStatus) validateBootConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.BootConfig) { // not required
		return nil
	}

	if m.BootConfig != nil {
		if err := m.BootConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("boot_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("boot_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateDiskList(formats strfmt.Registry) error {
	if swag.IsZero(m.DiskList) { // not required
		return nil
	}

	for i := 0; i < len(m.DiskList); i++ {
		if swag.IsZero(m.DiskList[i]) { // not required
			continue
		}

		if m.DiskList[i] != nil {
			if err := m.DiskList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("disk_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("disk_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) validateEffectiveStorageConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.EffectiveStorageConfig) { // not required
		return nil
	}

	if m.EffectiveStorageConfig != nil {
		if err := m.EffectiveStorageConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("effective_storage_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("effective_storage_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateGenerationUUID(formats strfmt.Registry) error {
	if swag.IsZero(m.GenerationUUID) { // not required
		return nil
	}

	if err := validate.Pattern("generation_uuid", "body", m.GenerationUUID, `^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$`); err != nil {
		return err
	}

	return nil
}

func (m *VMResourcesDefStatus) validateGpuList(formats strfmt.Registry) error {
	if swag.IsZero(m.GpuList) { // not required
		return nil
	}

	for i := 0; i < len(m.GpuList); i++ {
		if swag.IsZero(m.GpuList[i]) { // not required
			continue
		}

		if m.GpuList[i] != nil {
			if err := m.GpuList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("gpu_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("gpu_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) validateGuestCustomization(formats strfmt.Registry) error {
	if swag.IsZero(m.GuestCustomization) { // not required
		return nil
	}

	if m.GuestCustomization != nil {
		if err := m.GuestCustomization.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("guest_customization")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("guest_customization")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateGuestTools(formats strfmt.Registry) error {
	if swag.IsZero(m.GuestTools) { // not required
		return nil
	}

	if m.GuestTools != nil {
		if err := m.GuestTools.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("guest_tools")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("guest_tools")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateHostReference(formats strfmt.Registry) error {
	if swag.IsZero(m.HostReference) { // not required
		return nil
	}

	if m.HostReference != nil {
		if err := m.HostReference.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("host_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("host_reference")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateMemorySizeMib(formats strfmt.Registry) error {
	if swag.IsZero(m.MemorySizeMib) { // not required
		return nil
	}

	if err := validate.MinimumInt("memory_size_mib", "body", int64(m.MemorySizeMib), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *VMResourcesDefStatus) validateNicList(formats strfmt.Registry) error {
	if swag.IsZero(m.NicList) { // not required
		return nil
	}

	for i := 0; i < len(m.NicList); i++ {
		if swag.IsZero(m.NicList[i]) { // not required
			continue
		}

		if m.NicList[i] != nil {
			if err := m.NicList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nic_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("nic_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) validateNumThreadsPerCore(formats strfmt.Registry) error {
	if swag.IsZero(m.NumThreadsPerCore) { // not required
		return nil
	}

	if err := validate.MinimumInt("num_threads_per_core", "body", int64(m.NumThreadsPerCore), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *VMResourcesDefStatus) validateParentReference(formats strfmt.Registry) error {
	if swag.IsZero(m.ParentReference) { // not required
		return nil
	}

	if m.ParentReference != nil {
		if err := m.ParentReference.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parent_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parent_reference")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validatePowerStateMechanism(formats strfmt.Registry) error {
	if swag.IsZero(m.PowerStateMechanism) { // not required
		return nil
	}

	if m.PowerStateMechanism != nil {
		if err := m.PowerStateMechanism.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("power_state_mechanism")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("power_state_mechanism")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateProtectionPolicyState(formats strfmt.Registry) error {
	if swag.IsZero(m.ProtectionPolicyState) { // not required
		return nil
	}

	if m.ProtectionPolicyState != nil {
		if err := m.ProtectionPolicyState.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("protection_policy_state")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("protection_policy_state")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateRecoveryPlanStateList(formats strfmt.Registry) error {
	if swag.IsZero(m.RecoveryPlanStateList) { // not required
		return nil
	}

	for i := 0; i < len(m.RecoveryPlanStateList); i++ {
		if swag.IsZero(m.RecoveryPlanStateList[i]) { // not required
			continue
		}

		if m.RecoveryPlanStateList[i] != nil {
			if err := m.RecoveryPlanStateList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recovery_plan_state_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recovery_plan_state_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) validateSerialPortList(formats strfmt.Registry) error {
	if swag.IsZero(m.SerialPortList) { // not required
		return nil
	}

	for i := 0; i < len(m.SerialPortList); i++ {
		if swag.IsZero(m.SerialPortList[i]) { // not required
			continue
		}

		if m.SerialPortList[i] != nil {
			if err := m.SerialPortList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("serial_port_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("serial_port_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) validateStorageConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.StorageConfig) { // not required
		return nil
	}

	if m.StorageConfig != nil {
		if err := m.StorageConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("storage_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("storage_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateVnumaConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.VnumaConfig) { // not required
		return nil
	}

	if m.VnumaConfig != nil {
		if err := m.VnumaConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vnuma_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vnuma_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) validateVtpmConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.VtpmConfig) { // not required
		return nil
	}

	if m.VtpmConfig != nil {
		if err := m.VtpmConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vtpm_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vtpm_config")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this vm resources def status based on the context it is used
func (m *VMResourcesDefStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateApcConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateBootConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDiskList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEffectiveStorageConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateGpuList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateGuestCustomization(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateGuestTools(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHostReference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNicList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateParentReference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePowerStateMechanism(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProtectionPolicyState(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRecoveryPlanStateList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSerialPortList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStorageConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVnumaConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVtpmConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VMResourcesDefStatus) contextValidateApcConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.ApcConfig != nil {

		if swag.IsZero(m.ApcConfig) { // not required
			return nil
		}

		if err := m.ApcConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apc_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apc_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateBootConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.BootConfig != nil {

		if swag.IsZero(m.BootConfig) { // not required
			return nil
		}

		if err := m.BootConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("boot_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("boot_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateDiskList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DiskList); i++ {

		if m.DiskList[i] != nil {

			if swag.IsZero(m.DiskList[i]) { // not required
				return nil
			}

			if err := m.DiskList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("disk_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("disk_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateEffectiveStorageConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.EffectiveStorageConfig != nil {

		if swag.IsZero(m.EffectiveStorageConfig) { // not required
			return nil
		}

		if err := m.EffectiveStorageConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("effective_storage_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("effective_storage_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateGpuList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.GpuList); i++ {

		if m.GpuList[i] != nil {

			if swag.IsZero(m.GpuList[i]) { // not required
				return nil
			}

			if err := m.GpuList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("gpu_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("gpu_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateGuestCustomization(ctx context.Context, formats strfmt.Registry) error {

	if m.GuestCustomization != nil {

		if swag.IsZero(m.GuestCustomization) { // not required
			return nil
		}

		if err := m.GuestCustomization.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("guest_customization")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("guest_customization")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateGuestTools(ctx context.Context, formats strfmt.Registry) error {

	if m.GuestTools != nil {

		if swag.IsZero(m.GuestTools) { // not required
			return nil
		}

		if err := m.GuestTools.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("guest_tools")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("guest_tools")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateHostReference(ctx context.Context, formats strfmt.Registry) error {

	if m.HostReference != nil {

		if swag.IsZero(m.HostReference) { // not required
			return nil
		}

		if err := m.HostReference.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("host_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("host_reference")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateNicList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.NicList); i++ {

		if m.NicList[i] != nil {

			if swag.IsZero(m.NicList[i]) { // not required
				return nil
			}

			if err := m.NicList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nic_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("nic_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateParentReference(ctx context.Context, formats strfmt.Registry) error {

	if m.ParentReference != nil {

		if swag.IsZero(m.ParentReference) { // not required
			return nil
		}

		if err := m.ParentReference.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parent_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parent_reference")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidatePowerStateMechanism(ctx context.Context, formats strfmt.Registry) error {

	if m.PowerStateMechanism != nil {

		if swag.IsZero(m.PowerStateMechanism) { // not required
			return nil
		}

		if err := m.PowerStateMechanism.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("power_state_mechanism")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("power_state_mechanism")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateProtectionPolicyState(ctx context.Context, formats strfmt.Registry) error {

	if m.ProtectionPolicyState != nil {

		if swag.IsZero(m.ProtectionPolicyState) { // not required
			return nil
		}

		if err := m.ProtectionPolicyState.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("protection_policy_state")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("protection_policy_state")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateRecoveryPlanStateList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RecoveryPlanStateList); i++ {

		if m.RecoveryPlanStateList[i] != nil {

			if swag.IsZero(m.RecoveryPlanStateList[i]) { // not required
				return nil
			}

			if err := m.RecoveryPlanStateList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recovery_plan_state_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recovery_plan_state_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateSerialPortList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SerialPortList); i++ {

		if m.SerialPortList[i] != nil {

			if swag.IsZero(m.SerialPortList[i]) { // not required
				return nil
			}

			if err := m.SerialPortList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("serial_port_list" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("serial_port_list" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateStorageConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.StorageConfig != nil {

		if swag.IsZero(m.StorageConfig) { // not required
			return nil
		}

		if err := m.StorageConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("storage_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("storage_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateVnumaConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.VnumaConfig != nil {

		if swag.IsZero(m.VnumaConfig) { // not required
			return nil
		}

		if err := m.VnumaConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vnuma_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vnuma_config")
			}
			return err
		}
	}

	return nil
}

func (m *VMResourcesDefStatus) contextValidateVtpmConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.VtpmConfig != nil {

		if swag.IsZero(m.VtpmConfig) { // not required
			return nil
		}

		if err := m.VtpmConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vtpm_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vtpm_config")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VMResourcesDefStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VMResourcesDefStatus) UnmarshalBinary(b []byte) error {
	var res VMResourcesDefStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
