// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VMVtpmStatus VM vTPM configuration status.
//
// Current status of the vTPM configuration.
//
// swagger:model vm_vtpm_status
type VMVtpmStatus struct {

	// data source reference
	DataSourceReference *Reference `json:"data_source_reference,omitempty"`

	// Virtual trusted platform module version.
	Version string `json:"version,omitempty"`

	// Indicates whether virtual trusted platform module is enabled for the the Guest OS.
	//
	VtpmEnabled bool `json:"vtpm_enabled,omitempty"`
}

// Validate validates this vm vtpm status
func (m *VMVtpmStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDataSourceReference(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VMVtpmStatus) validateDataSourceReference(formats strfmt.Registry) error {
	if swag.IsZero(m.DataSourceReference) { // not required
		return nil
	}

	if m.DataSourceReference != nil {
		if err := m.DataSourceReference.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data_source_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data_source_reference")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this vm vtpm status based on the context it is used
func (m *VMVtpmStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDataSourceReference(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VMVtpmStatus) contextValidateDataSourceReference(ctx context.Context, formats strfmt.Registry) error {

	if m.DataSourceReference != nil {

		if swag.IsZero(m.DataSourceReference) { // not required
			return nil
		}

		if err := m.DataSourceReference.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data_source_reference")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("data_source_reference")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VMVtpmStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VMVtpmStatus) UnmarshalBinary(b []byte) error {
	var res VMVtpmStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
