// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VMVnumaConfig VM vNUMA configuration
//
// # Indicates how VM vNUMA should be configured
//
// swagger:model vm_vnuma_config
type VMVnumaConfig struct {

	// Number of vNUMA nodes. 0 means vNUMA is disabled.
	NumVnumaNodes int64 `json:"num_vnuma_nodes,omitempty"`
}

// Validate validates this vm vnuma config
func (m *VMVnumaConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vm vnuma config based on context it is used
func (m *VMVnumaConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VMVnumaConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VMVnumaConfig) UnmarshalBinary(b []byte) error {
	var res VMVnumaConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
