name: Makefile CI
env:
  EXPORT_RESULT: true
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
      
    - name: Install dependencies
      run: make vendor
      
    - name: Check build
      run: make build
    
    - name: Check linting
      run: make lint
      
    - name: Run tests
      run: make test
    
    - name: Prepare coverage report
      run: make coverage

